# Services for local development
services:
  postgresql:
    image: postgres:16
    environment:
      - POSTGRES_DB=proconnect_ep
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:5.0.23
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fc
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongodb:/init
    entrypoint: ["/init/entrypoint.sh"]
    tmpfs:
      - /data/db
      - /data/configdb

  mailcatcher:
    image: sj26/mailcatcher:latest
    ports:
      - "1081:1080"
      - "1025:1025"